export { default as Header } from './Header'
export { default as Introduction } from './Introduction'
export { default as Prices } from './Prices'
export { default as Payments } from './Payments'
export { default as Footer } from './Footer'